### ISSUE TITLE
Failed to save sys log event: could not execute batch

### ISSUE THREAD

**Issue by saidRaiss** [soffa-projects/foundation-java#3]
Using PostgreSQL 9.6 and Java 8 I got this error: **invalid input syntax for type timestamp: "17:07:04.041+01"**
```
io.soffa.foundation.exceptions.TechnicalException: could not execute batch; SQL [insert into sys_logs (application, created_at, data, duration, error, error_details, event, kind, request_id, span_id, trace_id, user_id, value, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; nested exception is org.hibernate.exception.DataException: could not execute batch
	at io.soffa.foundation.spring.config.SysLogRepositoryImpl.save(SysLogRepositoryImpl.java:26)
	at io.soffa.foundation.actions.DefaultActionDispatcher.lambda$logAction$6(DefaultActionDispatcher.java:163)
	at io.soffa.foundation.context.TenantHolder.lambda$submit$0(TenantHolder.java:74)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	...
Caused by: org.postgresql.util.PSQLException: ERROR: invalid input syntax for type timestamp: "17:07:04.041+01"
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2674)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2364)
```

```java
try {
      sysLogs.save(log);
} catch (Exception e) {
      LOG.error(e, "failed to save sys log event: %s", e.getMessage());
 }
```

Maybe we need to change createdAt type to SQL Date or LocalDateTime

```java
import java.util.Date;
// ...
public class SysLog {
      // ...
      private Date createdAt;
      // ...
```
```xml
<createTable tableName="${table_prefix}sys_logs">
      <!-- ... -->
      <column name="created_at" type="timestamp"/>
</createTable>
```
Referencies:
- https://jdbc.postgresql.org/documentation/head/8-date-time.html
- https://www.postgresql.org/docs/9.6/datatype-datetime.html

**Comment by titusgahissy** [comment]
Fixed in v1.2.5 
https://github.com/soffa-io/soffa-foundation/blob/6cc5152c2b20907f2f45855a0f6b98c969128cbe/soffa-foundation-core/src/main/java/io/soffa/foundation/data/entities/SysLogEntity.java#L33
